services:
  storybook-php:
    build:
      context: ..
      dockerfile: storybook/.docker/Dockerfile
    command: php -S 0.0.0.0:8000 -t public/
    volumes:
      - ./../:/autoupgrade
    working_dir: /autoupgrade/storybook
    ports:
      - "8003:8000"

  storybook-js:
    build:
      context: ..
      dockerfile: storybook/.docker/Dockerfile
    command: npm run storybook
    environment:
      IS_IN_DOCKER: true
    volumes:
      - ./../:/autoupgrade
    working_dir: /autoupgrade/storybook
    ports:
      - "6006:6006"
    depends_on:
      - storybook-php
