name: Autoupgrade Storybook CICD

concurrency:
  group: storybook-${{ github.ref }}

on:
  push:
    branches: 
      - dev
      - master
    tags: 
      - "*"


jobs: 
  storybook-repository-dispatch:
    name: Trigger Repository Dispatch
    runs-on: ubuntu-latest
    timeout-minutes: 10

  steps:

      - name: Get tag
        shell: bash
        id: get_tag
        run: echo TAG=$(echo $GITHUB_REF | cut -d / -f 3) >> $GITHUB_OUTPUT

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.AUTOUPGRADE_CD_PAT }}
          repository: ${{ secrets.AUTOUPGRADE_CD_REPOSITORY }}
          event-type: branch-${{ steps.extract_branch.outputs.branch }}
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "tag": "${{ steps.get_tag.outputs.TAG }}"}'
