name: UI Tests
on:
  ## Check each PR
  push:
  pull_request:
  ## Manual execution on branch
  workflow_dispatch:
  ## Nightly
  ### Needs secrets
  #### GC_PROJECT_ID
  #### GC_SERVICE_KEY
  #### NIGHTLY_TOKEN
  schedule:
    - cron: '0 0 * * *'
env:
  CAMPAIGN: 'autoupgrade'
jobs:
  ui_test:
    name: UI Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - PS_VERSION_START: 8.1.4
            PHP_VERSION: 7.2
          - PS_VERSION_START: 8.1.4
            PHP_VERSION: 7.3
    env:
      PS_DOCKER: ${{ matrix.PS_VERSION_START }}-${{ matrix.PHP_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Start containers
        working-directory: tests/UI/
        env:
          PS_VERSION: ${{ env.PS_DOCKER }}
        run: |
          docker compose -f "docker-compose.yml" up -d --build
          bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost/en/)" != "200" ]]; do sleep 5; done'

      - name: Composer install
        run: composer install

      - name: Install module autoupgrade
        working-directory: tests/UI/
        run: |
          docker exec -t prestashop php -v bin/console prestashop:module install autoupgrade

      - name: Download the latest version of Prestashop
        run: |
          docker exec -t prestashop mkdir admin-dev/autoupgrade/download
          docker exec -t prestashop curl -L https://github.com/PrestaShop/PrestaShop/releases/download/8.1.5/prestashop_8.1.5.zip -o admin-dev/autoupgrade/download/prestashop.zip
          docker exec -t prestashop curl -L https://github.com/PrestaShop/PrestaShop/releases/download/8.1.5/prestashop_8.1.5.xml -o admin-dev/autoupgrade/download/prestashop.xml

      - name: Upgrade
        run: |
         docker exec -t prestashop php modules/autoupgrade/tests/testCliProcess.php modules/autoupgrade/cli-upgrade.php  --dir=admin-dev --action=compareReleases
         docker exec -t prestashop php modules/autoupgrade/tests/testCliProcess.php modules/autoupgrade/cli-upgrade.php --dir=admin-dev

      - name: Install dependencies
        working-directory: tests/UI/
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: tests/UI/
        run: npx playwright install chromium --with-deps

      - name: Run Playwright tests
        working-directory: tests/UI/
        run: npx playwright test